### ISSUE TITLE
Have the translated output in the kill-ring

### ISSUE THREAD

**Issue by fniessen** [atykhonov/google-translate#30] opened 2015-01-13 09:32 UTC
Hello, when trying to automate (with an Emacs macro) the translation of terms in a column, I found it'd be good if GT would:
- unselect the selected region
- put the translation in the kill-ring (so that we simply have to press C-y to insert it somewhere)

Thanks!

**Comment by atykhonov** [comment] 2015-01-14 12:07
Hello @fniessen !

I'm sorry, but I didn't get you. The reason probably is: I'm not very proficient in Emacs (I use it during last 1.5 year only...). Could you please provide more details about automation which you performs, about what you're doing and what is expected result? Which data you have, which key-bindings you use and expected result. It would be also good if you'll provide your configuration for `google-translate`. So I'll be able to try the same situation and get clear vision of what you want to get.

Thank you.

**Comment by fniessen** [comment] 2015-01-14 19:42
Hello Andrey,

> Could you please provide more details about automation which you
> performs, about what you're doing and what is expected result? Which
> data you have, which key-bindings you use and expected result. It
> would be also good if you'll provide your configuration for
> `google-translate`. So I'll be able to try the same situation and get
> clear vision of what you want to get.

Suppose I have a table with two columns, such as:

    | fr     | en |
    |--------+----|
    | pomme  |    |
    | banane |    |
    | orange |    |

I'd like to define a macro that (for one row at a time) takes the
contents of the left column, ask Google Translate for the translation,
and goes insert it in the right column with C-y.

Defining a macro is made through `kmacro-start-macro' and
`kmacro-end-macro' (when finished recording it).

So, I would record:

- C-a to go at the beginning of the line,
- a couple of right-arrows to move across the pipe symbol,
- C-SPC to begin the selection of a region,
- moving with right-arrows to the end of the cell,
- calling google-translate,
- move to the next cell,
- insert the results (if in the kill ring) with C-y,
- go one line down (easier to repeat).

Something like that...

Calling it is made via kmacro-call-macro.

With the macro, I could simply apply it several times on the rows for
which I want a translation. So simple could it become.

Is this clear enough now?

Thanks for your work!

**Comment by atykhonov** [comment] 2015-01-15 00:25
Thank you very much for such detailed explanation! I didn't even thought in such direction and didn't imagine such use case before. You gave me very clear explanation.

I just finished the feature you requested. It is in the master branch already. You can checkout and try. Or you can update via melpa (please note I didn't pushed the changes into the marmalade, I hope this is not about your case). I hope that melpa will have updated version (0.10.6) very soon. And please let me know whether everything is fine and works as you expected!

How to use `google-translate` when you want to get translation to be inserted to the kill ring? There are two ways.

1) You need to change `google-translate-output-destination` setting (default value is `nil`):

```
(setq google-translate-output-destination 'kill-ring)
```
After that all your translations will be inserted to the kill ring!

After you'll finish automation you'll probably want to change `google-translate-output-destination` back to the old value.

2) You can directly execute the following command:

```
M-: (google-translate-translate "en" "de" (thing-at-point 'word) 'kill-ring) RET
```


I suppose that first way is most convenient way to do your automation. Please try and let me know.

P.S. About region deactivation: it deactivates after translation, so no problem with that.

**Comment by peterhoeg** [comment] 2016-09-26 02:54
I can confirm this works and the issue can be closed.

**Closed** 2020-06-09 06:17 UTC
