### ISSUE TITLE
how to make google-translate work in an erc buffer ?

### ISSUE THREAD

**Issue by pseudomyne** [atykhonov/google-translate#35] opened 2015-07-06 21:35 UTC
hi, 
GT works well here in a lisp buffer, in the scratch buffer, in any org buffer, but won't in an erc buffer. Messages buffer says : "Contacting host: translate.google.com:80 facemenu-add-face: Text is read-only", GT buffer gets cleared. Any help ?

**Comment by atykhonov** [comment] 2015-07-06 23:52
Hi!
It works well for me in erc buffer. I've just tested it. It would be great to have configuration (gt and probably erc) so that I'll be able to reproduce it and see what the issue and how it could be fixed.

**Comment by atykhonov** [comment] 2015-07-07 00:26
Could you provide the configuration?

**Comment by pseudomyne** [comment] 2015-07-07 09:21
Of course, see https://www.refheap.com/eb85cbb5fcb71ffce695105cb

**Comment by pseudomyne** [comment] 2015-07-07 09:23
(if you need it i may also paste my customization file, though it's (almost) cosmetics.)

**Comment by atykhonov** [comment] 2015-07-07 22:15
Thank you!

I've reproduced it. And it is reproducable with my configuration too. You use `google-translate-default-ui` but I use `google-translate-smooth-ui`. And surprisingly with `smooth-ui` it does work but not with `default-ui`.

Thank you for the bug report!

I'll be investigating what is the reason of it and try to fix it asap.

**Comment by atykhonov** [comment] 2015-07-07 23:44
Fixed in #36 !

**Closed by atykhonov** 2015-07-07 23:44 UTC
