### ISSUE TITLE
JSON readtable error

### ISSUE THREAD

**Issue by jmburgos** [atykhonov/google-translate#24] opened 2014-10-01 14:45 UTC
Hi Andrey,
I am getting a "JSON readtble error" when I try to use google-translate with a block of text larger than about 1080 characters.  Otherwise it works fine.

My .emacs file contains the following:

(require 'google-translate)
(require 'google-translate-smooth-ui)
(global-set-key "\C-ct" 'google-translate-smooth-translate)
(setq google-translate-translation-directions-alist '(("is" . "en")))

Any ideas why this is happening?
Many thanks,

Julian

**Comment by jagrg** [comment] 2015-04-09 10:42
I'm getting the same error. When I type `M-x google-translate-at-point`, this is what I get:

```
Debugger entered--Lisp error: (json-readtable-error)
  signal(json-readtable-error nil)
  json-read()
  json-read-from-string("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\n<html>\n<head><meta...
```

Any idea?

**Comment by atykhonov** [comment] 2015-04-09 11:14
Hello @jagrg !

I was getting the same error yesterday. I updated `google-translate` yesterday and it works fine for me today. I suppose you just need to update it. Please try and let me know whether everything is fine.

**Comment by atykhonov** [comment] 2015-04-09 11:15
The current version is 0.11.0.

**Comment by jagrg** [comment] 2015-04-09 11:24
The update fixed it, thanks!

**Comment by atykhonov** [comment] 2015-04-09 12:44
Great! Thanks

**Comment by lislon** [comment] 2015-10-03 20:01
I'v just got same error on 0.11.1
I sniffed the request and saw HTTP code *503 Service Unavaliable* with html message
> Our systems have detected unusual traffic from your computer network.  Please try your request again later.

**Comment by alezost** [comment] 2015-10-03 21:03
Ouch, the same for me.  Google doesn't like us :-(

**Comment by alezost** [comment] 2015-10-04 11:19
... and I don't have this problem anymore

**Comment by elandx** [comment] 2015-10-04 18:59
Ten minutes ago package works fine but now i got the same error ...

**Comment by momomo5717** [comment] 2015-10-14 02:44
Hello,

The same message appeared.

>Our systems have detected unusual traffic from your computer network. Please try your request again later.

I'm not sure why it occurred, but it seems this problem comes from query parameters in my environment.

I redefined `google-translate--request` with query parameters which Firefox sent and it works.

This is my workaround.

``` emacs-lisp
(defmacro google-translage-redef-google-translate--request (url-or-qparams)
  "Redefine `google-translate--request' from URL-OR-QPARAMS.
If you use qparams, query parameters not including \"tl\", \"sl\" and \"q\" is needed."
  (let ((g-query-params (cl-gensym "query-params"))
        (g-url-or-qparams (cl-gensym "url-or-qparams")))
    `(defun google-translate--request (source-language
                                       target-language
                                       text
                                       &optional for-test-purposes)
       (let* ((,g-url-or-qparams ,url-or-qparams)
              (,g-query-params
               (cl-delete-if
                (lambda (ls) (member (car ls) '("tl" "sl" "q")))
                (if (stringp ,g-url-or-qparams)
                    (mapcar (lambda (str) (cl-destructuring-bind
                                          (n v)
                                          (split-string str "=")
                                        (cons n v)))
                            (split-string (cadr (split-string ,g-url-or-qparams "?")) "&"))
                  ,g-url-or-qparams))))
         (google-translate--http-response-body
          (google-translate--format-request-url
           `(("sl" . ,source-language)
             ("tl" . ,target-language)
             ("q"  . ,text)
             ,@,g-query-params))
          for-test-purposes)))))

(google-translage-redef-google-translate--request
 ;; This url was copied at Network Monitor of Firefox.
 "https://translate.google.com/translate_a/single?client=t&sl=en&tl=ja&hl=ja&dt=bd&dt=ex&dt=ld&dt=md&dt=qca&dt=rw&dt=rm&dt=ss&dt=t&dt=at&ie=UTF-8&oe=UTF-8&source=bh&srcrom=0&ssel=3&tsel=6&otf=1&kc=5&tk=160396|290233&q=test")

;; (setq lexical-binding t) is needed before evaluating it.
(defun google-translate-redef-request-query-params (copied-url)
  (interactive "MInput url a web browser sent : ")
  (google-translage-redef-google-translate--request copied-url))
```

Thank you.

**Comment by lislon** [comment] 2015-10-14 14:56
Thank you @momomo5717! 
It worked for me for first time, but after second request I got same error again. After I changed url to my own, it works good so far.

**Comment by momomo5717** [comment] 2015-10-15 15:37
Thank you @lislon for the feedback!
>It worked for me for first time, but after second request I got same error again. After I changed url to my own, it works good so far.

That's good news for users getting the same error message.

Perhaps, https://translate.google.com/ might dispatch the url by IP or something.
So I suppose a url which is used in user's environment could be needed.

I hope there are common minimum query parameters.

Thank you.

**Comment by atykhonov** [comment] 2015-10-16 20:35
Hi all!

I've just recently fixed that issue! At least it doesn't appear for me. All integration tests successfully passed. Latest version is "v0.11.2". Please try it, please let me know if something is wrong, if it doesn't work.

Please note, this is quite expected issue, it can appear from time to time, so please, if you experience it, post the message here. I don't close this issue.

**Comment by lislon** [comment] 2015-10-22 19:08
@atykhonov Thank you for the new version. So far so good :thumbsup: Tested on 2 machines win & nix.

**Comment by atykhonov** [comment] 2015-10-22 22:12
@lislon thank you for the feedback! Nice to know!

**Comment by bzzup** [comment] 2015-10-24 14:50
I see you have added [tk] query parameter. Have you investigated what is that?

**Comment by miguelazo82** [comment] 2015-12-18 22:16
I had the same issue a few months ago - now it's back!   I believe when the error occurred last time I could at least resolve it by restarting emacs. Now it's permanent (well, since today).

Installed from emacs package manager - version (melpa) 20151016.1220

**Comment by atykhonov** [comment] 2015-12-19 00:12
@miguelazo82 , yes, for sorry it is back. Previous "JSON readtable error" were relate to the unappropriate parameters, but now, it seems, there is another cause. Please take a look at #39 .

**Comment by atykhonov** [comment] 2015-12-19 01:07
Hi @bzzup !

> @atykhonov I see you have added [tk] query parameter. Have you investigated what is that?

For sorry, I haven't investigated it. I've put random value and it was working fine with it. But now, it seems, it requires valid tk (it couldn't be random any more).

**Comment by atykhonov** [comment] 2015-12-19 01:08
P. S. I'm still investigating this issue.

**Comment by lislon** [comment] 2015-12-27 11:03
There is similar issue (with solution in python) https://github.com/soimort/translate-shell/issues/94

**Comment by momomo5717** [comment] 2015-12-28 02:17
@lislon Thank you for posting the link!

I tried translating the python and awk code into elisp,
and it works in my environment.


``` elisp
(defun google-translate--gen-rl (a b)
  (cl-loop for c from 0 below (- (length b) 2) by 3
           for d = (aref b (+ c 2)) do
           (setq d (if (>= d ?a) (- d 87) (- d ?0)))
           (setq d (if (= (aref b (1+ c)) ?+) (lsh a (- d)) (lsh a d)))
           (setq a (if (= (aref b c) ?+) (logand (+ a d) 4294967295) (logxor a d))))
  a)

(defun google-translate--gen-tk (text)
  (let* ((b (floor (/ (time-to-seconds) 3600)))
         (ub "+-3^+b+-f")
         (vb "+-a^+6")
         (a (cl-reduce (lambda (a e) (google-translate--gen-rl (+ a e) vb))
                       (encode-coding-string text 'utf-8) :initial-value b)))
    (setq a (google-translate--gen-rl a ub))
    (when (< a 0) (setq a (+ (logand a 2147483647) 2147483648)))
    (setq a (% a (floor 1e6)))
    (format "%s.%s" a (logxor a b))))

(defun google-translate--request (source-language
                                  target-language
                                  text
                                  &optional for-test-purposes)
  "Send to the Google Translate http request which consigned to
translate TEXT from SOURCE-LANGUAGE to TARGET-LANGUAGE."
  (google-translate--http-response-body
   (google-translate--format-request-url
    `(("client" . "t")
      ("ie"     . "UTF-8")
      ("oe"     . "UTF-8")
      ("sl"     . ,source-language)
      ("tl"     . ,target-language)
      ("q"      . ,text)
      ("dt"     . "bd")
      ("dt"     . "ex")
      ("dt"     . "ld")
      ("dt"     . "md")
      ("dt"     . "qc")
      ("dt"     . "rw")
      ("dt"     . "rm")
      ("dt"     . "ss")
      ("dt"     . "t")
      ("dt"     . "at")
      ("pc"     . "1")
      ("otf"    . "1")
      ("srcrom" . "1")
      ("ssel"   . "0")
      ("tsel"   . "0")
      ("tk"     . ,(google-translate--gen-tk text))))
   for-test-purposes))
```

Thank you.

**Comment by neutrous** [comment] 2016-01-01 15:25
I have met the same error with version 0.11.2...

any suggestion?

**Comment by jagrg** [comment] 2016-01-01 18:01
@neutrous, did you try momomo5717's solution above? I have the same version and it worked for me.

**Comment by neutrous** [comment] 2016-01-04 01:35
@jagrg @momomo5717 Great! The solution works well! It would be nice to merge the code into the upstream?

**Comment by atykhonov** [comment] 2016-01-04 12:33
@momomo5717 thank you very much for the patch!

I've just committed it into the master. 

Please checkout the newest v0.11.3 version.

**Comment by momomo5717** [comment] 2016-01-04 17:42
@jagrg @neutrous Thank you for trying it! I'm happy it works for you.

@atykhonov Thank you for adding it! I'm glad I could be of help.
The new version works fine.

It seems  `google-translate-format-listen-url` also needs `tk` like the following:

``` elisp
(defun google-translate-format-listen-url (text language)
  "Format listen url for TEXT and TARGET-LANGUAGE."
  (google-translate--format-listen-url `(("ie"      . "UTF-8")
                                         ("q"       . ,text)
                                         ("tl"      . ,language)
                                         ("total"   . "1")
                                         ("idx"     . "0")
                                         ("textlen" . ,(number-to-string (length text)))
                                         ("client"  . "t")
                                         ("prev"    . "input")
                                         ("tk"      . ,(google-translate--gen-tk text)))))
```

Thank you.

**Comment by atykhonov** [comment] 2016-01-11 15:56
@momomo5717 thank you!

I've committed fix for listening in the latest v0.11.5 version.

**Comment by xtk923** [comment] 2016-05-11 18:25
Hello, I've installed the latest version 20160510.1535 and I got the same error for all functions of this package:

json-read: JSON readtable error

**Comment by atykhonov** [comment] 2016-05-11 21:07
Hello! The same for me.

```
(let ((source-language "en")
      (target-language "ru")
      (text "book"))
  (google-translate--insert-nulls
   (google-translate--request source-language target-language text)))
```

Returns

```
"<!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content=\"initial-scale=1, minimum-scale=1, width=device-width\">
  <title>Error 403 (Forbidden)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>403.</b> <ins>That’s an error.</ins>
  <p>Your client does not have permission to get URL <code>/translate_a/single?client=t&amp;ie=UTF-8&amp;oe=UTF-8&amp;sl=en&amp;tl=ru&amp;q=book&amp;dt=bd&amp;dt=ex&amp;dt=ld&amp;dt=md&amp;dt=qc&amp;dt=rw&amp;dt=rm&amp;dt=ss&amp;dt=t&amp;dt=at&amp;pc=1&amp;otf=1&amp;srcrom=1&amp;ssel=0&amp;tsel=0&amp;tk=841167.714426</code> from this server.  <ins>That’s all we know.</ins>
"
```

I'm looking for the fix...

**Comment by atykhonov** [comment] 2016-05-12 14:21
@momomo5717 helped again to resolve that issue.

The newest version (with the fix): v0.11.9.

@xtk923 @jagrg  could you please try it?

**Comment by jtkDvlp** [comment] 2016-05-12 16:13
Hi!

I got the same problem, found this issue and tried newest version v0.11.9 but now my emacs freeze at message "Opening TLS connection to `translate.google.com'...done" :-$

Anybody got the same?

**Comment by xtk923** [comment] 2016-05-12 17:06
@atykhonov I upgraded the package and the problem remains

The following are the only relevant messaged I got:

Contacting host: translate.google.com:80
json-read: JSON readtable error

**Comment by atykhonov** [comment] 2016-05-12 20:23
@jtkDvlp @xtk923 thanks for the feedbacks!

Could you please update again, so that you should receive the latest `0.11.10` version? Then, could you please execute: `M-x google-translate-version RET` ? Obviously, it will return current version, so that I'll be sure that that latest version is in use. I'm sorry for asking this, but otherwise, it means that I need to consider re-implementation of `google-translate-tk` feature (not easy task) with hope that that will help us to avoid mentioned errors.

Thank you in advance!

**Comment by xtk923** [comment] 2016-05-12 21:49
@atykhonov The error is solved. Thanks for the maintenance!

**Comment by atykhonov** [comment] 2016-05-12 22:39
@xtk923 great, thank you!

**Comment by jtkDvlp** [comment] 2016-05-12 23:03
Does not work for me. Tried on clean emacs installation. Got the right version with 'google-translate-version but still got a frozen emacs with last info "Opening TLS connection to `translate.google.com'...done"

**Comment by atykhonov** [comment] 2016-05-13 22:33
@jtkDvlp I've just prepared the latest v0.11.11 ( thanks to @momomo5717 and his #51 ). Could you please try again and let us know whether everything works fine for you now?

**Comment by jtkDvlp** [comment] 2016-05-14 21:38
I found out that´s working on linux but not on windows for me. I dont know why, but I tested on two different windows-systems an both got an frozen emacs. Test on linux was fine.

**Comment by momomo5717** [comment] 2016-05-16 14:25
Hello @jtkDvlp,

Thank you for testing on three different environment!
Sorry I can't test on windows.
Could you test the following code?
``` elisp
(url-retrieve-synchronously "https://translate.google.com/")
```
Thank you.

**Comment by jtkDvlp** [comment] 2016-05-17 07:23
I tested the function and it failed with the given message. I searched for an solution and found [this](http://xn--9dbdkw.se/diary/how_to_enable_GnuTLS_for_Emacs_24_on_Windows/index.en.html). Now it works for me, but there were no need for me to configure any trusted files (I dont know why there was no need for, maybe you can explain?)

Hope that helps.

**Comment by momomo5717** [comment] 2016-05-18 04:03
@jtkDvlp Thank you for testing again!

>(I dont know why there was no need for, maybe you can explain?)

Sorry I'm not sure.

Your solution is very helpful. Thank you!

**Comment by alphapapa** [comment] 2016-10-08 11:23
I'm guessing this can be closed.  I was on an old version and got this error, but it went away when I upgraded to the current version.  :)

**Comment by bmuhia** [comment] 2017-01-23 09:55
I just installed `google-translate`, and got the same error `JSON readtable error` while trying to translate the following text from Russian:

`В  силу  технических  особенностей 64-битная версия Windows 7 с данной
сборки  не  может  быть  установлена  Обновлением  на 64-битную версию
Windows   Vista/7.   Однако,  остается  возможность  инициировать  так
называемую    Выборочную    установку.   При   запуске   установки   с
DVD/USB-устройства,  как  с  загрузочного  носителя, все просто. А вот
чтобы   инициировать   установку   из-под   64-битной  ОС,  необходимо
стартовать  ее  не через setup.exe в корне носителя с дистрибутивом, а
через  setup.exe, что расположен в папке Sources дистрибутива. Autorun
установочного носителя при запуске из-под имеющейся ОС, выберет нужный
тип  старта сам. Если имеющаяся система работает в режиме EFI/UEFI, то
запустить  из-под  нее  установку  невозможно  и  в  режиме Выборочной
установки.`

**Comment by stardiviner** [comment] 2020-06-09 06:27
I think the problem is fixed in latest version. If someone still got this problem, comment bellow.

**Closed** 2020-06-09 06:27 UTC

**Comment by AllTheLife** [comment] 2022-01-28 09:42
I got this problem just now.
I tried to translate something, but I got the error: `json-read: JSON readtable error: 60`

I wrote this in my `init.el`
``` emacs-lisp
  (use-package google-translate
    :demand t
    :init
    (require 'google-translate)
    :functions (my-google-translate-at-point google-translate--search-tkk)
    :custom
    (google-translate-backend-method 'curl)
    :config
    (defun google-translate--search-tkk () "Search TKK." (list 430675 2721866130))
    (defun my-google-translate-at-point()
      "reverse translate if prefix"
      (interactive)
      (if current-prefix-arg
          (google-translate-at-point)
        (google-translate-at-point-reverse)))
    :bind
    ("C-c T". my-google-translate-at-point))
```
